### ISSUE TITLE
indentHTML not detecting self-closing img tags

### ISSUE THREAD

**Issue by renatodc** [zebzhao/indent.js#3]
The third master-rule should include self-closing img tags. Otherwise it skips an indentation on the tag.
{
            langs: "html",
            name: "link|br|input|meta|img",
            startToken: [/\<(link|br|input|meta|img)/i],
            endToken: [/>/],
            advance: true
        },

**Comment by zebzhao** [comment]
Thanks. I added hr and img to that rule. #4
