### ISSUE TITLE
Switch statement default block is not indented

### ISSUE THREAD

**Issue by OldSneerJaw** [zebzhao/indent.js#5]
Consider the following snippet:

```javascript
#!/usr/bin/env node

var indent = require('indent.js');
var input = 'switch (foo) {\n case \'bar\':\nbaz = foo;\nfoo = null;\nbreak;\ndefault:\nbaz = null;\n}';

console.log(indent.indentJS(input, '  '));
```

I would expect the output to indent the `default` block's body (i.e. `baz = null;`) by two characters, but the actual output uses the same indentation as the preceding line:

```javascript
switch (foo) {
  case 'bar':
    baz = foo;
    foo = null;
  break;
  default:
  baz = null;
}
```

Also, arguably the `break` statement should be indented by two characters to match the indentation of the `case` block's body.

**Comment by zebzhao** [comment]
Yes, I missed this scenario as the code I tested it with did not contain default...

Anyways, I made a commit the the latest develop branch ab5a81dcd80f1802a8cae8dca1e27f9b888badd1

If you do not find anymore problems with the solution, I'll release a new version. I also followed your suggestion of putting the break on the same indent as the rest of the block.

**Comment by OldSneerJaw** [comment]
Looks good to me. Thanks for the lightning fast turnaround time!
