### ISSUE TITLE
Switch statement default option is incorrectly indented following a return

### ISSUE THREAD

**Issue by OldSneerJaw** [zebzhao/indent.js#6]
Consider the following snippet:

```javascript
#!/usr/bin/env node

var indent = require('indent.js');
var input = 'switch (foo) {\ncase \'bar\':\nreturn baz;\ncase \'baz\':\nreturn qux;\ndefault:\nreturn null;\n}';

console.log(indent.indentJS(input, '  '));
```

I would expect the output to line up the `default` statement with each of the `case` statements above it, but the actual output uses the same indentation as the preceding line:

```javascript
switch (foo) {
  case 'bar':
    return baz;
  case 'baz':
    return qux;
    default:
    return null;
}
```

**Comment by zebzhao** [comment]
I believe this issue should also be fixed in the latest commit on develop e8ab83a3a5cbd4fdfec580b4cac418fb2cc4d99c.

If you have no further problems, I will merge this with master.

EDIT: Some further refinements added for return statement.

**Comment by OldSneerJaw** [comment]
It seems to be working as expected. Thanks again for the quick fix!

**Comment by zebzhao** [comment]
Cool. I'll merge this then and make a new release then. Thanks for pointing out these issues :)
